disabled_rules:
  - function_body_length
  - type_body_length

opt_in_rules: # some rules are only opt-in
  - empty_count
  - implicitly_unwrapped_optional

excluded: # paths to ignore during linting. Takes precedence over included.
- Carthage
- Pods

force_cast: warning
line_length: 120

file_length:
  warning: 500
  error: 1200

identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: # excluded via string
